# Generated by Django 5.1.5 on 2025-01-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_receipe_receipe_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
